export const sage_journals = [
"Advances in Communication and Swallowing",
"Algorithmic Finance",
"Applied Ontology",
"Asymptotic Analysis",
"Bio-Medical Materials and Engineering",
"Biorheology",
"Bridge Structures - Assessment, Design & Construction",
"Clinical Hemorheology and Microcirculation",
"Computability",
"Education for Information",
"Environmental Policy and Law",
"Fundamenta Informaticae",
"Human Antibodies",
"Human Systems Management",
"ICGA Journal",
"Information Polity",
"Information Services and Use",
"Integrated Computer-Aided Engineering",
"Intelligent Data Analysis",
"Intelligent Decision Technologies",
"Intelligenza Artificiale",
"International Journal of Applied Electromagnetics and Mechanics",
"International Journal of Developmental Science",
"International Journal of Hybrid Intelligent Systems",
"International Journal of Knowledge-Based and Intelligent Engineering Systems",
"International Journal of RF Technologies: Research and Applications",
"International Journal of Risk & Safety in Medicine",
"International Shipbuilding Progress",
"Isokinetics and Exercise Science",
"Journal of Alzheimer's Disease",
"Journal of Ambient Intelligence and Smart Environments",
"Journal of Back and Musculoskeletal Rehabilitation",
"Journal of Berry Research",
"Journal of Cellular Biotechnology",
"Journal of Computational Methods in Science and Engineering",
"Journal of Computer Security",
"Journal of Economic and Social Measurement",
"Journal of High Speed Networks",
"Journal of Huntington's Disease",
"Journal of Integrated Design and Process Science",
"Journal of Intelligent and Fuzzy Systems",
"Journal of Neonatal-Perinatal Medicine",
"Journal of Neutron Research",
"Journal of Smart Cities and Society",
"Journal of Vestibular Research",
"Journal of Vocational Rehabilitation",
"Journal of X-Ray Science and Technology",
"Main Group Chemistry",
"Mediterranean Journal of Nutrition and Metabolism",
"Model Assisted Statistics and Applications",
"Multiagent and Grid Systems",
"NeuroRehabilitation",
"Physiotherapy Practice and Research",
"Restorative Neurology and Neuroscience",
"Risk and Decision Analysis",
"Statistical Journal of the IAOS: Journal of the International Association for Official Statistics",
"Strength, Fracture and Complexity",
"Technology and Disability",
"Technology and Health Care",
"The European Journal on Artificial Intelligence",
"Translational Science of Rare Diseases",
"Web Intelligence",
"Work: A Journal of Prevention, Assessment and Rehabilitation",
]
