const sage_journals = [
"Journal",
"Abhigyan",
"About Campus",
"Academic Forensic Pathology",
"Accounting History",
"Acta Radiologica",
"Acta Sociologica",
"Action Research",
"Active Learning in Higher Education",
"Acupuncture & Electro-Therapeutics Research",
"Acupuncture in Medicine",
"Adaptive Behavior",
"ADCES in Practice",
"Administration & Society",
"Administrative Science Quarterly",
"Adoption & Fostering",
"Adult Education Quarterly",
"Adult Learning",
"Advances in Applied Ceramics",
"Advances in Communication and Swallowing",
"Advances in Dental Research",
"Advances in Developing Human Resources",
"Advances in Structural Engineering",
"Affilia",
"Agrarian South: Journal of Political Economy",
"Alexandria",
"Algorithmic Finance",
"Alternative Law Journal",
"AlterNative: An International Journal of Indigenous Peoples",
"Alternatives",
"Alternatives to Laboratory Animals",
"American Behavioral Scientist",
"American Economist",
"American Educational Research Journal",
"American Journal of Evaluation",
"American Journal of Health Promotion",
"American Journal of Hospice and Palliative Medicine",
"American Journal of Lifestyle Medicine",
"American Journal of Rhinology & Allergy",
"American Journal of Sports Medicine, The",
"American Politics Research",
"American Sociological Review",
"American String Teacher",
"American Surgeon",
"Anaesthesia and Intensive Care",
"Angiology",
"Anglican Theological Review",
"Animation",
"Annals of Clinical Biochemistry",
"Annals of Clinical Psychiatry",
"Annals of Otology, Rhinology, and Laryngology",
"Annals of Pharmacotherapy",
"ANNALS of the American Academy of Political and Social Science, The",
"Annals of the ICRP",
"Anthropocene Review, The",
"Anthropological Theory",
"Antitrust Bulletin",
"Antyajaa",
"Applied Earth Science",
"Applied Ontology",
"Applied Psychological Measurement",
"Applied Spectroscopy",
"Archive for the Psychology of Religion",
"Armed Forces & Society",
"Arthaniti",
"Arts and Humanities in Higher Education",
"Asia Pacific Journal of Public Health",
"Asian and Pacific Migration Journal",
"Asian Cardiovascular and Thoracic Annals",
"Asian Journal of Comparative Politics",
"Asian Journal of Legal Education",
"Asian Journal of Management Cases",
"Asia-Pacific Journal of Management Research and Innovation",
"Asia-Pacific Journal of Rural Development",
"Assessment",
"Assessment for Effective Intervention",
"Asymptotic Analysis",
"Australasian Journal of Early Childhood",
"Australasian Marketing Journal",
"Australasian Psychiatry",
"Australian and New Zealand Journal of Psychiatry",
"Australian Journal of Career Development",
"Australian Journal of Education",
"Australian Journal of Management",
"Autism",
"Avian Biology Research",
"Behavior Modification",
"Behavioral Disorders",
"Belonging",
"Beyond Behavior",
"Bible Translator, The",
"Biblical Theology Bulletin",
"Biological Research For Nursing",
"Bio-Medical Materials and Engineering",
"Biorheology",
"Bioscope: South Asian Screen Studies",
"BMS - Bulletin de Methodologie Sociologique",
"Body & Society",
"Bridge Structures - Assessment, Design & Construction",
"British Journal of Music Therapy",
"British Journal of Occupational Therapy, The",
"British Journal of Pain",
"British Journal of Politics and International Relations",
"British Journal of Visual Impairment",
"Building Acoustics",
"Building Services Engineering Research and Technology",
"Bulletin of Science, Technology & Society",
"Business & Society",
"Business and Professional Communication Quarterly",
"Business Information Review",
"Business Perspectives and Research",
"Cahiers Élisabéthains",
"Calcutta Statistical Association Bulletin",
"California Management Review",
"Canadian Association of Radiologists Journal",
"Canadian Journal of Nursing Research",
"Canadian Journal of Occupational Therapy",
"Canadian Journal of School Psychology",
"Canadian Pharmacists Journal",
"Capital and Class",
"Career Development and Transition for Exceptional Individuals",
"Cellular Polymers",
"Child Language Teaching and Therapy",
"Child Maltreatment",
"Childhood",
"China Information",
"China Report",
"Chinese Journal of Sociology",
"Chinese Journal of Transnational Law",
"Chinese Public Administration Review",
"Christian Education Journal",
"Chronic Illness",
"Citizenship, Social and Economics Education",
"City & Community",
"Clin-Alert",
"Clinical Case Studies",
"Clinical Child Psychology and Psychiatry",
"Clinical EEG and Neuroscience",
"Clinical Ethics",
"Clinical Hemorheology and Microcirculation",
"Clinical Medicine Insights: Arthritis and Musculoskeletal Disorders",
"Clinical Medicine Insights: Pediatrics",
"Clinical Nursing Research",
"Clinical Pediatrics",
"Clinical Practice in Pediatric Psychology",
"Clinical Psychological Science",
"Clinical Rehabilitation",
"Clinical Trials",
"Clothing and Textiles Research Journal",
"Coastal Studies & Society",
"Collections",
"Common Law World Review",
"Communication and Sport",
"Communication Disorders Quarterly",
"Communication Research",
"Community College Review",
"Community Dental Health",
"Community Health Equity Research & Policy",
"Comparative Political Studies",
"Compensation & Benefits Review",
"Competition and Change",
"Competition and Regulation in Network Industries",
"Computability",
"Concurrent Engineering",
"Conflict Management and Peace Science",
"Contemporary Drug Problems",
"Contemporary Education Dialogue",
"Contemporary Issues in Early Childhood",
"Contemporary Review of the Middle East",
"Contemporary Sociology: A Journal of Reviews",
"Contemporary Voice of Dalit",
"Contexts",
"Contributions to Indian Sociology",
"Convergence",
"Cooperation and Conflict",
"Cornell Hospitality Quarterly",
"Corrosion Engineering, Science and Technology",
"Counseling Psychologist, The",
"Creative Nursing",
"Crime & Delinquency",
"Crime, Media, Culture: An International Journal",
"Criminal Justice and Behavior",
"Criminal Justice Policy Review",
"Criminal Justice Review",
"Criminology & Criminal Justice",
"Critical Research on Religion",
"Critical Social Policy",
"Critical Sociology",
"Critical Studies in Television",
"Critique of Anthropology",
"Cross-Cultural Research",
"Cultural Dynamics",
"Cultural Geographies",
"Cultural Sociology",
"Cultural Studies <=> Critical Methodologies",
"Culture & Psychology",
"Culture and Education",
"Current Directions in Psychological Science",
"Current Sociology",
"Currents in Biblical Research",
"Dementia",
"Developmental Child Welfare",
"Dialogues in Human Geography",
"Dialogues in Sociology",
"Dialogues in Urban Research",
"Dialogues on Climate Change",
"Dialogues on Digital Society",
"Discourse & Communication",
"Discourse & Society",
"Discourse Studies",
"DIY, Alternative Cultures & Society",
"DMS - The Journal of Defense Modeling and Simulation",
"Downside Review",
"Drug Science, Policy and Law",
"Earthquake Spectra",
"East European Politics and Societies",
"Economic and Industrial Democracy",
"Economic Development Quarterly",
"Education and Urban Society",
"Education for Information",
"Education, Citizenship and Social Justice",
"Educational Administration Quarterly",
"Educational and Psychological Measurement",
"Educational Evaluation and Policy Analysis",
"Educational Management Administration & Leadership",
"Educational Policy",
"Educational Researcher",
"E-Learning and Digital Media",
"Electronic News",
"Emerging Adulthood",
"Emerging Economy Studies",
"Emotion Review",
"Empirical Studies of the Arts",
"Energy & Environment",
"Energy Journal, The",
"Entrepreneurship Education and Pedagogy",
"Entrepreneurship, Theory & Practice",
"Environment and Behavior",
"Environment and Planning A",
"Environment and Planning B",
"Environment and Planning C",
"Environment and Planning D",
"Environment and Planning E",
"Environment and Planning F",
"Environment and Security",
"Environment and Urbanization",
"Environment and Urbanization Asia",
"Environmental Law Review",
"Environmental Policy and Law",
"Environmental Values",
"Equity in Education & Society",
"Ergonomics in Design: The Quarterly of Human Factors Applications",
"Ethnicities",
"Ethnography",
"European Educational Research Journal",
"European History Quarterly",
"European Journal of Communication",
"European Journal of Criminology",
"European Journal of Cultural Studies",
"European Journal of Industrial Relations",
"European Journal of International Relations",
"European Journal of Mass Spectrometry",
"European Journal of Ophthalmology",
"European Journal of Personality",
"European Journal of Political Theory",
"European Journal of Probation",
"European Journal of Social Security",
"European Journal of Social Theory",
"European Journal of Women's Studies",
"European Labour Law Journal",
"European Physical Education Review",
"European Stroke Journal",
"European Union Politics",
"European Urban and Regional Studies",
"Evaluation",
"Evaluation & the Health Professions",
"Evaluation Journal of Australasia",
"Evaluation Review",
"Exceptional Children",
"Expository Times",
"FACE",
"Families in Society",
"Family Business Review",
"Family Journal, The",
"Feminism & Psychology",
"Feminist Criminology",
"Feminist Review",
"Feminist Theology",
"Feminist Theory",
"Field Methods",
"FIIB Business Review",
"First Language",
"Focus on Autism and Other Developmental Disabilities",
"Food and Nutrition Bulletin",
"Food Science and Technology International",
"Foot & Ankle International",
"Foot and Ankle Specialist",
"Foregut",
"Foreign Trade Review",
"Forum Italicum",
"French Cultural Studies",
"Fundamenta Informaticae",
"Games and Culture",
"Gender & Society",
"German Journal of Human Resource Management",
"Gifted Child Quarterly",
"Gifted Child Today",
"Gifted Education International",
"Global Business Review",
"Global Health Promotion",
"Global Journal of Emerging Market Economies",
"Global Media and Communication",
"Global Social Policy",
"Global Studies of Childhood",
"Group & Organization Management",
"Group Analysis",
"Group Processes & Intergroup Relations",
"Hand",
"Hand Therapy",
"Health Education & Behavior",
"Health Education Journal",
"Health Information Management Journal",
"Health Promotion Practice",
"Health Services Management Research",
"Health: An Interdisciplinary Journal",
"Healthcare Management Forum",
"HERD: Health Environments Research & Design Journal",
"High Performance Polymers",
"Higher Education for the Future",
"HIP International",
"Hispanic Health Care International",
"Hispanic Journal of Behavioral Sciences",
"History and Sociology of South Asia",
"History of Psychiatry",
"History of Science",
"History of the Human Sciences",
"Holocene, The",
"Home Health Care Management & Practice",
"Homicide Studies",
"Hospital Pharmacy",
"HSS Journal: The Musculoskeletal Journal of Hospital for Special Surgery",
"Human Antibodies",
"Human Factors",
"Human Geography",
"Human Relations",
"Human Resource Development Review",
"Human Systems",
"Human Systems Management",
"Humanity & Society",
"ICGA Journal",
"IFLA Journal",
"IIM Kozhikode Society & Management Review",
"Illness, Crisis & Loss",
"ILRReview",
"Imagination, Cognition and Personality",
"Improving Schools",
"Incarceration",
"Inclusive Practices",
"India Quarterly: A Journal of International Affairs",
"Indian Economic and Social History Review",
"Indian Economic Journal, The",
"Indian Historical Review",
"Indian Journal of Clinical Medicine",
"Indian Journal of Corporate Governance",
"Indian Journal of Gender Studies",
"Indian Journal of Human Development",
"Indian Journal of Public Administration",
"Indoor and Built Environment",
"Industry and Higher Education",
"Information Development",
"Information Polity",
"Information Services and Use",
"Information Visualization",
"Innovations: Technology and Techniques in Cardiothoracic and Vascular Surgery",
"Insight on Africa",
"Institutionalised Children Explorations and Beyond",
"Integrated Computer-Aided Engineering",
"Intelligent Data Analysis",
"Intelligent Decision Technologies",
"Intelligenza Artificiale",
"Interdisciplinary Science Reviews",
"International Bulletin of Mission Research",
"International Communication Gazette",
"International Criminal Justice Review",
"International Journal",
"International Journal of Aeroacoustics",
"International Journal of Applied Electromagnetics and Mechanics",
"International Journal of Architectural Computing",
"International Journal of Artificial Organs, The",
"International Journal of Behavioral Development",
"International Journal of Bilingualism",
"International Journal of Business Communication",
"International Journal of Care Coordination",
"International Journal of Christianity & Education",
"International Journal of Clinical Metabolism and Diabetes",
"International Journal of Commerce and Contracting",
"International Journal of Community and Social Development, The",
"International Journal of Comparative Sociology",
"International Journal of Cross Cultural Management",
"International Journal of Cultural Studies",
"International Journal of Damage Mechanics",
"International Journal of Developmental Science",
"International Journal of Discrimination and the Law",
"International Journal of Educational Reform",
"International Journal of Electrical Engineering & Education",
"International Journal of Engine Research",
"International Journal of Entrepreneurship and Innovation",
"International Journal of Forensic Mental Health",
"International Journal of High Performance Computing Applications",
"International Journal of Hybrid Intelligent Systems",
"International Journal of Knowledge-Based and Intelligent Engineering Systems",
"International Journal of Lower Extremity Wounds, The",
"International Journal of Maritime History",
"International Journal of Market Research",
"International Journal of Mass Emergencies & Disasters",
"International Journal of Mechanical Engineering Education",
"International Journal of Music Education",
"International Journal of Offender Therapy and Comparative Criminology",
"International Journal of Police Science and Management",
"International Journal of Press/Politics, The",
"International Journal of Protective Structures",
"International Journal of Psychiatry in Medicine, The",
"International Journal of RF Technologies: Research and Applications",
"International Journal of Risk & Safety in Medicine",
"International Journal of Robotics Research",
"International Journal of Rural Management",
"International Journal of Social Determinants of Health and Health Services",
"International Journal of Social Psychiatry",
"International Journal of Social Psychology",
"International Journal of Space Structures",
"International Journal of Sports Science & Coaching",
"International Journal of Spray and Combustion Dynamics",
"International Journal of STD & AIDS",
"International Journal of Stroke",
"International Journal of Surgical Pathology",
"International Journal of Toxicology",
"International Journal of Tryptophan Research",
"International Materials Reviews",
"International Migration Review",
"International Political Science Review / Revue internationale de science politique",
"International Regional Science Review",
"International Relations",
"International Review for the Sociology of Sport",
"International Review of Administrative Sciences",
"International Review of Qualitative Research",
"International Review of Victimology",
"International Shipbuilding Progress",
"International Small Business Journal",
"International Social Work",
"International Sociology",
"International Studies",
"International Wood Products Journal",
"Interpretation",
"Intervention in School and Clinic",
"Interventional Neuroradiology",
"Irish Economic and Social History",
"Irish Journal of Sociology",
"Irish Theological Quarterly",
"Ironmaking & Steelmaking",
"Isokinetics and Exercise Science",
"Jadavpur Journal of International Relations",
"JDR Clinical and Translational Research",
"Jindal Management Journal",
"Journal for the Education of the Gifted",
"Journal for the History of Astronomy",
"Journal for the Study of Education and Development",
"Journal for the Study of the New Testament",
"Journal for the Study of the Old Testament",
"Journal for the Study of the Pseudepigrapha",
"Journal for Vascular Ultrasound",
"Journal of Accounting, Auditing & Finance",
"Journal of Adolescent Research",
"Journal of Adult and Continuing Education",
"Journal of Advanced Academics",
"Journal of Advanced Oral Research",
"Journal of Advertising Education",
"Journal of Aging and Health",
"Journal of Alternative Finance",
"Journal of Alzheimer's Disease",
"Journal of Ambient Intelligence and Smart Environments",
"Journal of Applied Behavioral Science, The",
"Journal of Applied Gerontology",
"Journal of Applied Social Science",
"Journal of Asian and African Studies",
"Journal of Asian Economic Integration",
"Journal of Asian Security and International Affairs",
"Journal of Attention Disorders",
"Journal of Back and Musculoskeletal Rehabilitation",
"Journal of Berry Research",
"Journal of Bioactive and Compatible Polymers",
"Journal of Biological Rhythms",
"Journal of Biomaterials Applications",
"Journal of Black Psychology",
"Journal of Black Studies",
"Journal of Building Physics",
"Journal of Business and Technical Communication",
"Journal of Career Assessment",
"Journal of Career Development",
"Journal of Cases in Educational Leadership",
"Journal of Cellular Biotechnology",
"Journal of Cellular Plastics",
"Journal of Cerebral Blood Flow and Metabolism",
"Journal of Child Health Care",
"Journal of Child Neurology",
"Journal of Chinese Writing Systems",
"Journal of Classical Sociology",
"Journal of Clinical Urology",
"Journal of Cognitive Engineering and Decision Making",
"Journal of College Student Retention: Research, Theory & Practice",
"Journal of Communication Inquiry",
"Journal of Composite Materials",
"Journal of Computational Methods in Science and Engineering",
"Journal of Computer Security",
"Journal of Conflict Resolution",
"Journal of Consumer Culture",
"Journal of Contemporary Criminal Justice",
"Journal of Contemporary Ethnography",
"Journal of Contemporary History",
"Journal of Creating Value",
"Journal of Creative Communications",
"Journal of Criminal Law, The",
"Journal of Criminology",
"Journal of Cross-Cultural Psychology",
"Journal of Cultural Management and Cultural Policy",
"Journal of Cutaneous Medicine and Surgery",
"Journal of Dance Medicine Science",
"Journal of Dental Research",
"Journal of Developing Societies",
"Journal of Development Policy and Practice",
"Journal of Diabetes Science and Technology",
"Journal of Diagnostic Medical Sonography",
"Journal of Disability Policy Studies",
"Journal of Drug Education: Substance Abuse Research and Prevention",
"Journal of Drug Issues",
"Journal of Early Adolescence, The",
"Journal of Early Childhood Literacy",
"Journal of Early Childhood Research",
"Journal of Early Intervention",
"Journal of Economic and Social Measurement",
"Journal of Education",
"Journal of Education for Sustainable Development",
"Journal of Educational and Behavioral Statistics",
"Journal of Educational Computing Research",
"Journal of Educational Technology Systems",
"Journal of Egyptian Archaeology",
"Journal of Elastomers and Plastics",
"Journal of Emerging Market Finance",
"Journal of Emotional and Behavioral Disorders",
"Journal of Empirical Research on Human Research Ethics",
"Journal of Endometriosis and Pelvic Pain Disorders",
"Journal of Endovascular Therapy",
"Journal of English Linguistics",
"Journal of Entrepreneurship",
"Journal of Entrepreneurship and Innovation in Emerging Economies",
"Journal of Environment & Development, The",
"Journal of Ethnobiology",
"Journal of European Social Policy",
"Journal of European Studies",
"Journal of Experiential Education",
"Journal of Family History",
"Journal of Family Issues",
"Journal of Family Nursing",
"Journal of Fire Sciences",
"Journal of General Management",
"Journal of General Music Education",
"Journal of Generic Medicines",
"Journal of Geriatric Psychiatry and Neurology",
"Journal of Hand Surgery (European Volume)",
"Journal of Health and Human Services Administration",
"Journal of Health and Social Behavior",
"Journal of Health Management",
"Journal of Health Psychology",
"Journal of Health Services Research & Policy",
"Journal of Heritage Management",
"Journal of High Speed Networks",
"Journal of Hispanic Higher Education",
"Journal of Histochemistry & Cytochemistry",
"Journal of Historical Research in Music Education",
"Journal of Holistic Nursing",
"Journal of Hospitality & Tourism Cases",
"Journal of Hospitality & Tourism Research",
"Journal of Human Lactation",
"Journal of Human Values",
"Journal of Humanistic Psychology",
"Journal of Huntington's Disease",
"Journal of Industrial Relations",
"Journal of Infection Prevention",
"Journal of Information Science",
"Journal of Information Technology",
"Journal of Information Technology Teaching Cases",
"Journal of Infrastructure Development",
"Journal of Integrated Design and Process Science",
"Journal of Intellectual Disabilities",
"Journal of Intelligent and Fuzzy Systems",
"Journal of Intelligent Material Systems and Structures",
"Journal of Intensive Care Medicine",
"Journal of Interactive Marketing",
"Journal of Interdisciplinary Economics",
"Journal of Interior Design",
"Journal of International Marketing",
"Journal of International Political Theory",
"Journal of Interpersonal Violence",
"Journal of Interpretation Research",
"Journal of Investigative Medicine",
"Journal of Land and Rural Studies",
"Journal of Language and Social Psychology",
"Journal of Leadership & Organizational Studies",
"Journal of Learning Disabilities",
"Journal of Librarianship and Information Science",
"Journal of Literacy Research",
"Journal of Macromarketing",
"Journal of Management",
"Journal of Management Education",
"Journal of Management Inquiry",
"Journal of Management Scientific Reports",
"Journal of Marketing",
"Journal of Marketing Education",
"Journal of Marketing Research",
"Journal of Material Culture",
"Journal of Medical Biography",
"Journal of Medical Screening",
"Journal of Men's Studies",
"Journal of Micromanufacturing",
"Journal of Mixed Methods Research",
"Journal of Modern European History",
"Journal of Music Teacher Education",
"Journal of Near Infrared Spectroscopy",
"Journal of Neonatal-Perinatal Medicine",
"Journal of Neonatology",
"Journal of Neutron Research",
"Journal of Oncology Pharmacy Practice",
"Journal of Onco-Nephrology",
"Journal of Operations and Strategic Planning",
"Journal of Orthodontics",
"Journal of Palliative Care",
"Journal of Pastoral Care & Counseling",
"Journal of Patient Safety and Risk Management",
"Journal of Peace Research",
"Journal of Peacebuilding & Development",
"Journal of Pediatric Hematology/Oncology Nursing",
"Journal of Pediatric Surgical Nursing",
"Journal of Perioperative Practice",
"Journal of Pharmacy Practice",
"Journal of Pharmacy Technology",
"Journal of Planning Education and Research",
"Journal of Planning History",
"Journal of Planning Literature",
"Journal of Plastic Film and Sheeting",
"Journal of Positive Behavior Interventions",
"Journal of Prevention and Health Promotion",
"Journal of Psoriasis and Psoriatic Arthritis",
"Journal of Psychoeducational Assessment",
"Journal of Psychologists and Counsellors in Schools",
"Journal of Psychology and Theology",
"Journal of Psychopharmacology",
"Journal of Public Policy & Marketing",
"Journal of Reinforced Plastics and Composites",
"Journal of Research in Crime and Delinquency",
"Journal of Research in International Education",
"Journal of Research in Music Education",
"Journal of Research in Nursing",
"Journal of Research on Leadership Education",
"Journal of Sandwich Structures and Materials",
"Journal of School Leadership",
"Journal of School Nursing",
"Journal of Scleroderma and Related Disorders",
"Journal of Service Research",
"Journal of Smart Cities and Society",
"Journal of Smart Tourism",
"Journal of Social and Personal Relationships",
"Journal of Social Archaeology",
"Journal of Social Inclusion Studies",
"Journal of Social Studies Research, The",
"Journal of Social Work",
"Journal of Sociology",
"Journal of South Asian Development",
"Journal of Special Education Technology",
"Journal of Special Education, The",
"Journal of Spiritual Formation and Soul Care",
"Journal of Sport and Social Issues",
"Journal of Sports Economics",
"Journal of Strain Analysis for Engineering Design, The",
"Journal of Stroke Medicine",
"Journal of Studies in International Education",
"Journal of Teacher Education",
"Journal of Technical Writing and Communication",
"Journal of Telemedicine and Telecare",
"Journal of the American Psychiatric Nurses Association",
"Journal of the American Psychoanalytic Association",
"Journal of the Anthropological Survey of India",
"Journal of the Intensive Care Society",
"Journal of the Renin-Angiotensin-Aldosterone System",
"Journal of the Royal College of Physicians of Edinburgh",
"Journal of the Royal Society of Medicine",
"Journal of Theoretical Politics",
"Journal of Thermoplastic Composite Materials",
"Journal of Transcultural Nursing",
"Journal of Transformative Education",
"Journal of Travel Research",
"Journal of Tropical Futures",
"Journal of Urban History",
"Journal of Vacation Marketing",
"Journal of Vestibular Research",
"Journal of Veterinary Dentistry",
"Journal of Veterinary Diagnostic Investigation",
"Journal of Vibration and Control",
"Journal of Victimology and Victim Justice",
"Journal of Visual Culture",
"Journal of Visual Impairment & Blindness",
"Journal of VitreoRetinal Diseases",
"Journal of Vocational Rehabilitation",
"Journal of White Collar and Corporate Crime",
"Journal of World Affairs: Voice of the Global South",
"Journal of X-Ray Science and Technology",
"Journal on Migration and Human Security",
"Journalism",
"Journalism & Communication Monographs",
"Journalism & Mass Communication Educator",
"Journalism & Mass Communication Quarterly",
"JRSM Cardiovascular Disease",
"Labor Studies Journal",
"Laboratory Animals",
"Language and Literature",
"Language and Speech",
"Language Teaching Research",
"Language Testing",
"Latin American Perspectives",
"Law, Culture and the Humanities",
"Leadership",
"Learning Disabilities Research and Practice",
"Learning Disability Quarterly",
"Lighting Research & Technology",
"Linacre Quarterly",
"Literacy Research",
"Literature and History",
"Literature, Critique, and Empire Today",
"Local Economy",
"Lupus",
"Maastricht Journal of European and Comparative Law",
"Main Group Chemistry",
"Management and Business Review",
"Management and Labour Studies",
"Management Communication Quarterly",
"Management in Education",
"Management Learning",
"Management Teaching Review",
"Margin - The Journal of Applied Economic Research",
"Marketing Theory",
"Materials Science and Technology",
"Mathematics & Mechanics of Solids",
"Media International Australia",
"Media Watch",
"Media, Culture & Society",
"Media, War & Conflict",
"Medical Care Research and Review",
"Medical Decision Making",
"Medical Law International",
"Medicine, Science and the Law",
"Medico-Legal Journal",
"Medieval History Journal, The",
"Mediterranean Journal of Nutrition and Metabolism",
"Memory Studies",
"Men and Masculinities",
"Metamorphosis: A Journal of Management Research",
"Migration and Development",
"Millennial Asia",
"Millennium: Journal of International Studies",
"Mineral Processing and Extractive Metallurgy",
"Mining Technology",
"Missiology",
"Mobile Media & Communication",
"Model Assisted Statistics and Applications",
"Modern China",
"Multiagent and Grid Systems",
"Multimodality & Society",
"Multiple Sclerosis Journal",
"Music Educators Journal",
"Musicae Scientiae",
"NASN School Nurse",
"Netherlands Quarterly of Human Rights",
"Neurohospitalist, The",
"Neuroradiology Journal, The",
"NeuroRehabilitation",
"Neurorehabilitation and Neural Repair",
"Neuroscientist, The",
"New Horizons in Adult Education & Human Resource Development",
"New Journal of European Criminal Law",
"New Labor Forum",
"New Media & Society",
"New Perspectives",
"NEW SOLUTIONS: A Journal of Environmental and Occupational Health Policy",
"News Research Journal",
"NHRD Network Journal",
"Nineteenth Century Theatre and Film",
"NIR News",
"Noise & Vibration Worldwide",
"Nonprofit and Voluntary Sector Quarterly",
"North American Archaeologist",
"Nursing & Midwifery Research Journal",
"Nursing Ethics",
"Nursing Science Quarterly",
"Nutrition and Health",
"Obstetric Medicine",
"OMEGA - Journal of Death and Dying",
"Organization",
"Organization & Environment",
"Organization Studies",
"Organizational Psychology Review",
"Organizational Research Methods",
"Oriental Anthropologist",
"OTJR: Occupational Therapy Journal of Research",
"Outlook on Agriculture",
"Palliative Medicine",
"Paradigm: A Management Research Journal",
"Party Politics",
"Pedagogy in Health Promotion",
"Pediatric and Developmental Pathology",
"Perception",
"Perceptual and Motor Skills",
"Perfusion",
"Peritoneal Dialysis International",
"Personality and Social Psychology Bulletin",
"Personality and Social Psychology Review",
"Perspectives in Public Health",
"Perspectives on Psychological Science",
"Philosophy & Social Criticism",
"Philosophy of the Social Sciences",
"Phlebology",
"Physiotherapy Practice and Research",
"Planning Theory",
"Plastic Surgery",
"Plastics, Rubber and Composites",
"Police Journal: Theory, Practice and Principles",
"Police Quarterly",
"Policy Futures in Education",
"Policy Insights from the Behavioral and Brain Sciences",
"Policy, Politics, & Nursing Practice",
"Political Research Quarterly",
"Political Studies",
"Political Studies Review",
"Political Theory",
"Politics",
"Politics & Society",
"Politics, Philosophy & Economics",
"Polymers from Renewable Resources",
"Possibility Studies & Society",
"Post Reproductive Health",
"Powder Metallurgy",
"Primary Dental Journal",
"Prison Journal, The",
"Pro Ecclesia",
"Probation Journal",
"Proceedings of the Human Factors and Ergonomics Society Annual Meeting",
"Proceedings of the Institution of Mechanical Engineers, Part A: Journal of Power and Energy",
"Proceedings of the Institution of Mechanical Engineers, Part B: Journal of Engineering Manufacture",
"Proceedings of the Institution of Mechanical Engineers, Part C: Journal of Mechanical Engineering Science",
"Proceedings of the Institution of Mechanical Engineers, Part D: Journal of Automobile Engineering",
"Proceedings of the Institution of Mechanical Engineers, Part E: Journal of Process Mechanical Engineering",
"Proceedings of the Institution of Mechanical Engineers, Part F: Journal of Rail and Rapid Transit",
"Proceedings of the Institution of Mechanical Engineers, Part G: Journal of Aerospace Engineering",
"Proceedings of the Institution of Mechanical Engineers, Part H: Journal of Engineering in Medicine",
"Proceedings of the Institution of Mechanical Engineers, Part I: Journal of Systems and Control Engineering",
"Proceedings of the Institution of Mechanical Engineers, Part J: Journal of Engineering Tribology",
"Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-Body Dynamics",
"Proceedings of the Institution of Mechanical Engineers, Part L: Journal of Materials: Design and Applications",
"Proceedings of the Institution of Mechanical Engineers, Part M: Journal of Engineering for the Maritime Environment",
"Proceedings of the Institution of Mechanical Engineers, Part N: Journal of Nanomaterials, Nanoengineering and Nanosystems",
"Proceedings of the Institution of Mechanical Engineers, Part O: Journal of Risk and Reliability",
"Proceedings of the Institution of Mechanical Engineers, Part P: Journal of Sports Engineering and Technology",
"Proceedings of the International Symposium on Human Factors and Ergonomics in Healthcare",
"Production and Operations Management",
"Professional School Counseling",
"Progress in Development Studies",
"Progress in Environmental Geography",
"Progress in Human Geography",
"Progress in Physical Geography",
"Progress in Rubber, Plastics and Recycling Technology",
"Progress in Transplantation",
"Project Management Journal",
"Psychological Reports",
"Psychological Science",
"Psychological Science in the Public Interest",
"Psychology and Developing Societies",
"Psychology Learning & Teaching",
"Psychology of Music",
"Psychology of Women Quarterly",
"PsyEcology",
"Public Administration Quarterly",
"Public Finance and Management",
"Public Finance Review",
"Public Health Reports",
"Public Personnel Management",
"Public Policy and Administration",
"Public Relations Inquiry",
"Public Understanding of Science",
"Public Works Management & Policy",
"Punishment & Society",
"Qualitative Health Research",
"Qualitative Inquiry",
"Qualitative Research",
"Qualitative Social Work",
"Quantum Economics and Finance",
"Quarterly Journal of Experimental Psychology",
"Race & Class",
"Race and Justice",
"Rationality and Society",
"Recherche et Applications en Marketing",
"Recherche et Applications en Marketing (English Edition)",
"Recreational Sports Journal",
"Rehabilitation Counseling Bulletin",
"RELC Journal",
"Remedial and Special Education",
"Research and Practice for Persons with Severe Disabilities",
"Research in Comparative and International Education",
"Research in Education",
"Research Methods in Medicine & Health Sciences",
"Research on Aging",
"Research on Social Work Practice",
"Research Studies in Music Education",
"Restorative Neurology and Neuroscience",
"Review & Expositor",
"Review of Black Political Economy",
"Review of Development and Change",
"Review of Educational Research",
"Review of General Psychology",
"Review of Market Integration",
"Review of Public Personnel Administration",
"Review of Radical Political Economics",
"Review of Religious Research",
"Review of Research in Education",
"Risk and Decision Analysis",
"Rural Special Education Quarterly",
"Scandinavian Journal of Public Health",
"School Psychology International",
"Science & Society",
"Science and Technology of Welding and Joining",
"Science Communication",
"Science of Diabetes Self-Management and Care, The",
"Science Technology and Society",
"Science, Technology & Human Values",
"Scottish Medical Journal",
"Second Language Research",
"Security Dialogue",
"Seminars in Cardiothoracic and Vascular Anesthesia",
"Sex & Sexualities",
"Sexual Abuse",
"Sexualities",
"Shoulder & Elbow",
"Simulation & Gaming",
"SIMULATION: Transactions of The Society for Modeling and Simulation International",
"Small Enterprises Development, Management & Extension Journal",
"Small Group Research",
"Social & Legal Studies",
"Social Change",
"Social Compass",
"Social Currents",
"Social Marketing Quarterly",
"Social Psychological and Personality Science",
"Social Psychology Quarterly",
"Social Science Computer Review",
"Social Science Information",
"Social Studies of Science",
"Society and Culture in South Asia",
"Society and Mental Health",
"Sociological Bulletin",
"Sociological Methodology",
"Sociological Methods & Research",
"Sociological Perspectives",
"Sociological Research Online",
"Sociological Review",
"Sociological Theory",
"Sociology",
"Sociology of Education",
"Sociology of Race and Ethnicity",
"South African Journal of Psychology",
"South Asia Economic Journal",
"South Asia Research",
"South Asian Journal of Business and Management Cases",
"South Asian Journal of Human Resources Management",
"South Asian Journal Of Macroeconomics And Public Finance",
"South Asian Survey",
"Space and Culture",
"Sports Health",
"Stata Journal, The",
"State and Local Government Review",
"Statistical Journal of the IAOS: Journal of the International Association for Official Statistics",
"Statistical Methods in Medical Research",
"Statistical Modelling",
"Strategic Organization",
"Strength, Fracture and Complexity",
"String Research Journal",
"Structural Health Monitoring",
"Studia Liturgica",
"Studies in Christian Ethics",
"Studies in History",
"Studies in Indian Politics",
"Studies in Microeconomics",
"Studies in People’s History",
"Studies in Psychology",
"Studies in Religion / Sciences Religieuses",
"Substance Use and Addiction Journal",
"Surface Engineering",
"Surgical Innovation",
"Teacher Education and Special Education",
"Teachers College Record",
"Teaching Exceptional Children",
"Teaching of Psychology",
"Teaching Public Administration",
"Teaching Sociology",
"Technology and Disability",
"Technology and Health Care",
"Television & New Media",
"Textile Research Journal",
"The American Journal of Cosmetic Surgery",
"The American Review of Public Administration",
"The Canadian Journal of Psychiatry",
"The Cleft Palate Craniofacial Journal",
"The European Journal on Artificial Intelligence",
"The International Journal of Aging and Human Development",
"The International Journal of Evidence & Proof",
"The Journal of Transport History",
"The Journal of Vascular Access",
"Theological Studies",
"Theology",
"Theology Today",
"Theoretical Criminology",
"Theory & Psychology",
"Theory and Research in Education",
"Theory, Culture & Society",
"Thesis Eleven",
"Time & Society",
"Topics in Early Childhood Special Education",
"Tourism and Hospitality Research",
"Tourism Economics",
"Tourist Studies",
"Toxicologic Pathology",
"Toxicology and Industrial Health",
"Transactions in Earth, Environment, and Sustainability",
"Transactions in Energy and Sustainability",
"Transactions in Planning and Urban Research",
"Transactions in Urban Data, Science, and Technology",
"Transactions of the Institute of Measurement and Control",
"Transcultural Psychiatry",
"Transfer - European Review of Labour and Research",
"Transformation",
"Translational Science of Rare Diseases",
"Transportation Research Record",
"Trauma",
"Trauma, Violence, & Abuse",
"Tribology - Materials, Surfaces & Interfaces",
"Tropical Conservation Science",
"Tropical Doctor",
"Tumori Journal",
"Ultrasonic Imaging",
"Ultrasound",
"UPDATE: Applications of Research in Music Education",
"Urban Affairs Review",
"Urban Education",
"Urban Political Ecology",
"Urban Studies",
"Urbanisation",
"Urologia Journal",
"Vascular",
"Vascular and Endovascular Surgery",
"Vascular Medicine",
"Veterinary Pathology",
"Violence Against Women",
"Violence: An International Journal",
"Vision",
"Visual Communication",
"War in History",
"Waste Management and Research",
"Web Intelligence",
"Western Journal of Nursing Research",
"Wilderness & Environmental Medicine",
"Wind Engineering",
"Word of Mouth",
"Work and Occupations",
"Work, Employment & Society",
"Work: A Journal of Prevention, Assessment and Rehabilitation",
"Workplace Health & Safety",
"World Futures Review",
"World Journal for Pediatric and Congenital Heart Surgery",
"Written Communication",
"Young Exceptional Children",
"Youth & Society",
"Youth Justice",
"Youth Violence and Juvenile Justice",
"Last updated: 17/12/2024",
]
