export const wiley_journals = [
"Abacus",
"Academic Emergency Medicine",
"Accounting & Finance",
"Accounting Perspectives",
"Acta Anaesthesiologica Scandinavica",
"Acta Crystallographica Section A: Foundations and Advances",
"Acta Crystallographica Section B: Structural Science, Crystal Engineering and Materials",
"Acta Crystallographica Section C: Structural Chemistry",
"Acta Crystallographica Section D: Structural Biology",
"Acta Crystallographica Section F: Structural Biology Communications",
"Acta Geologica Sinica (English Edition)",
"Acta Ophthalmologica",
"Acta Paediatrica",
"Acta Physiologica",
"Acta Psychiatrica Scandinavica",
"Acta Zoologica",
"Addiction",
"Advanced Biology",
"Advanced Control for Applications: Engineering and Industrial Systems ",
"Advanced Energy Materials",
"Advanced Engineering Materials",
"Advanced Functional Materials",
"Advanced Healthcare Materials",
"Advanced Materials",
"Advanced Materials Technologies",
"Advanced Optical Materials",
"Advanced Quantum Technologies",
"Advanced Sustainable Systems",
"Advanced Synthesis & Catalysis",
"Advanced Theory and Simulations",
"Advanced Therapeutics",
"Advances in Digestive Medicine",
"AEM Education and Training",
"African Development Review",
"African Journal of Ecology",
"Aggressive Behavior",
"Agribusiness",
"Agricultural and Forest Entomology",
"Agricultural Economics",
"Agronomy Journal",
"AIChE Journal",
"Alcohol, Clinical and Experimental Research",
"Alimentary Pharmacology & Therapeutics",
"Allergy",
"American Anthropologist",
"American Business Law Journal",
"American Ethnologist",
"American Journal of Agricultural Economics",
"American Journal of Biological Anthropology",
"American Journal of Botany",
"American Journal of Community Psychology",
"American Journal of Hematology",
"American Journal of Human Biology",
"American Journal of Industrial Medicine",
"American Journal of Medical Genetics Part A",
"American Journal of Medical Genetics Part B: Neuropsychiatric Genetics",
"American Journal of Medical Genetics Part C: Seminars in Medical Genetics",
"American Journal of Political Science",
"American Journal of Primatology",
"American Journal of Reproductive Immunology",
"Anaesthesia",
"Anaesthesia Reports",
"Analyses of Social Issues and Public Policy",
"Analysis & Sensing",
"Analytic Philosophy",
"Anatomia, Histologia, Embryologia",
"Anatomical Sciences Education",
"Andrology",
"Angewandte Chemie",
"Angewandte Chemie International Edition",
"Animal Conservation",
"Animal Genetics",
"Animal Science Journal",
"Annalen der Physik",
"Annals of Anthropological Practice",
"Annals of Applied Biology",
"Annals of Human Genetics",
"Annals of Neurology",
"Annals of Public and Cooperative Economics",
"Annals of the New York Academy of Sciences",
"Anthropology & Education Quarterly",
"Anthropology and Humanism",
"Anthropology of Consciousness",
"Anthropology of Work Review",
"Anthropology Today",
"Antipode",
"ANZ Journal of Surgery",
"AORN Journal",
"APMIS",
"Applied Cognitive Psychology",
"Applied Economic Perspectives and Policy",
"Applied Organometallic Chemistry",
"Applied Psychology",
"Applied Psychology: Health and Well-Being",
"Applied Research",
"Applied Stochastic Models in Business and Industry",
"Applied Vegetation Science",
"Aquatic Conservation: Marine and Freshwater Ecosystems",
"Arabian Archaeology and Epigraphy",
"Archaeological Papers of the American Anthropological Association",
"Archaeological Prospection",
"Archaeology in Oceania",
"Archaeometry",
"Archiv der Pharmazie",
"Archives of Insect Biochemistry and Physiology",
"Area",
"Arthritis & Rheumatology",
"Arthritis Care & Research",
"Artificial Organs",
"Asia Pacific Journal of Human Resources",
"Asia Pacific Viewpoint",
"Asian Economic Journal",
"Asian Economic Policy Review",
"Asian Journal of Control",
"Asian Journal of Endoscopic Surgery",
"Asian Journal of Organic Chemistry",
"Asian Journal of Social Psychology",
"Asian Politics & Policy",
"Asian Social Work and Policy Review",
"Asian-Pacific Economic Literature",
"Asia-Pacific Economic History Review",
"Asia-Pacific Journal of Chemical Engineering",
"Asia-Pacific Journal of Clinical Oncology",
"Asia-Pacific Journal of Financial Studies",
"Asia-Pacific Psychiatry",
"Astronomische Nachrichten",
"Austral Ecology",
"Austral Entomology",
"Australasian Journal of Dermatology",
"Australasian Journal of Ultrasound in Medicine",
"Australasian Journal on Ageing",
"Australian & New Zealand Journal of Statistics",
"Australian Accounting Review",
"Australian and New Zealand Journal of Family Therapy",
"Australian and New Zealand Journal of Obstetrics and Gynaecology",
"Australian Dental Journal",
"Australian Economic Papers",
"Australian Endodontic Journal",
"Australian Journal of Politics and History",
"Australian Journal of Public Administration",
"Australian Journal of Rural Health",
"Australian Journal of Social Issues",
"Australian Occupational Therapy Journal",
"Australian Veterinary Journal",
"Autism Research",
"AWWA Water Science",
"Basic & Clinical Pharmacology & Toxicology",
"Basin Research",
"Batteries & Supercaps",
"Behavioral Interventions",
"Behavioral Sciences & the Law",
"Berichte zur Wissenschaftsgeschichte",
"Biochemistry and Molecular Biology Education",
"Bioelectromagnetics",
"BioEssays",
"Bioethics",
"BioFactors",
"Biofuels, Bioproducts and Biorefining",
"Biological Reviews",
"Biology of the Cell",
"Biomedical Chromatography",
"Biometrical Journal",
"Biopharmaceutics & Drug Disposition",
"Biopolymers",
"Biotechnology and Applied Biochemistry",
"Biotechnology and Bioengineering",
"Biotechnology Journal",
"Biotechnology Progress",
"Biotropica",
"Bipolar Disorders",
"Birth",
"Birth Defects Research",
"BJOG: An International Journal of Obstetrics and Gynaecology",
"BJU International",
"British Educational Research Journal",
"British Journal of Clinical Pharmacology",
"British Journal of Clinical Psychology",
"British Journal of Developmental Psychology",
"British Journal of Educational Psychology",
"British Journal of Educational Technology",
"British Journal of Haematology",
"British Journal of Health Psychology",
"British Journal of Industrial Relations",
"British Journal of Learning Disabilities",
"British Journal of Management",
"British Journal of Mathematical and Statistical Psychology",
"British Journal of Pharmacology",
"British Journal of Psychology",
"British Journal of Psychotherapy",
"British Journal of Social Psychology",
"British Journal of Special Education",
"Bulletin of Economic Research",
"Bulletin of Latin American Research",
"Bulletin of the Korean Chemical Society",
"Bulletin of the London Mathematical Society",
"Business and Society Review",
"Business Ethics, the Environment & Responsibility",
"Business Strategy and Development",
"Business Strategy and the Environment",
"Canadian Geographies / Les géographies canadiennes",
"Canadian Journal of Administrative Sciences / Revue Canadienne des Sciences de l'Administration",
"Canadian Journal of Agricultural Economics/Revue canadienne d'agroeconomie",
"Canadian Journal of Economics/Revue canadienne d'économique",
"Canadian Public Administration",
"Canadian Review of Sociology/Revue canadienne de sociologie",
"Cancer",
"Cancer Cytopathology",
"Catheterization and Cardiovascular Interventions",
"ce/papers",
"Cell Biochemistry and Function",
"Cell Biology International",
"Cereal Chemistry",
"ChemBioChem",
"ChemBioEng Reviews",
"ChemCatChem",
"Chemical Biology & Drug Design",
"Chemical Engineering & Technology",
"Chemie Ingenieur Technik",
"Chemistry - A European Journal",
"Chemistry - An Asian Journal",
"Chemistry & Biodiversity",
"ChemistrySelect",
"ChemKon",
"ChemMedChem",
"CHEMNANOMAT",
"ChemPhotoChem",
"ChemPhysChem",
"ChemPlusChem",
"ChemSusChem",
"ChemSystemsChem",
"Child & Family Social Work",
"Child Abuse Review",
"Child and Adolescent Mental Health",
"Child Development",
"Child Development Perspectives",
"Child: Care, Health and Development",
"Children & Society",
"China & World Economy",
"Chinese Journal of Chemistry",
"Chirality",
"City & Society",
"Civil Engineering Design",
"Cladistics",
"CLEAN - Soil, Air, Water",
"Clinical & Experimental Allergy",
"Clinical & Experimental Ophthalmology",
"Clinical Advances in Periodontics",
"Clinical Anatomy",
"Clinical and Experimental Neuroimmunology",
"Clinical and Experimental Pharmacology and Physiology",
"Clinical Endocrinology",
"Clinical Genetics",
"Clinical Implant Dentistry and Related Research",
"Clinical Obesity",
"Clinical Oral Implants Research",
"Clinical Otolaryngology",
"Clinical Pharmacology & Therapeutics",
"Clinical Pharmacology in Drug Development",
"Clinical Physiology and Functional Imaging",
"Clinical Psychology & Psychotherapy",
"Clinical Transplantation",
"Cochrane Library* (Not eligible for APC coverage through a Transitional Deal)",
"Cognitive Science",
"Color Research and Application",
"Coloration Technology",
"Colorectal Disease",
"Communications on Pure and Applied Mathematics",
"Community Dentistry and Oral Epidemiology",
"Comprehensive Reviews in Food Science and Food Safety",
"Computational Intelligence",
"Computer Animation and Virtual Worlds",
"Computer Applications In Engineering Education",
"Computer Graphics Forum",
"Computer-Aided Civil and Infrastructure Engineering",
"Concurrency and Computation: Practice and Experience",
"Conflict Resolution Quarterly",
"Congenital Anomalies",
"Conservation Biology",
"Constellations",
"Consumer Psychology Review",
"Contact Dermatitis",
"Contemporary Accounting Research",
"Contemporary Economic Policy",
"Contributions to Plasma Physics",
"Corporate Governance: An International Review",
"Corporate Social Responsibility and Environmental Management",
"Counselling and Psychotherapy Research",
"Counselor Education and Supervision",
"Creativity and Innovation Management",
"Criminal Behaviour and Mental Health",
"Criminology",
"Criminology & Public Policy",
"Critical Quarterly",
"Crop Science",
"Crop, Forage & Turfgrass Management",
"Crystal Research and Technology",
"Culture, Agriculture, Food and Environment",
"Curator: The Museum Journal",
"Current Protocols",
"Curtis's Botanical Magazine",
"Cytometry Part A",
"Cytometry Part B: Clinical Cytometry",
"Cytopathology",
"Cytoskeleton",
"Decision Sciences",
"Decision Sciences Journal of Innovative Education",
"Dental Traumatology",
"Dermatological Reviews",
"Developing World Bioethics",
"Development and Change",
"Development Policy Review",
"Development, Growth & Differentiation",
"Developmental Dynamics",
"Developmental Medicine & Child Neurology",
"Developmental Neurobiology",
"Developmental Psychobiology",
"Developmental Science",
"Diabetes, Obesity and Metabolism",
"Diabetes/Metabolism Research and Reviews",
"Diabetic Medicine",
"Diagnostic Cytopathology",
"Dialog",
"Die Unterrichtspraxis/Teaching German",
"Digest of Middle East Studies",
"Digestive Endoscopy",
"Disasters",
"Drug and Alcohol Review",
"Drug Development Research",
"Drug Testing and Analysis",
"Dyslexia",
"Early Intervention in Psychiatry",
"Early Medieval Europe",
"Earth Surface Processes and Landforms",
"Earthquake Engineering & Structural Dynamics",
"Earthquake Engineering and Resilience",
"Echocardiography",
"Ecohydrology",
"Ecological Applications",
"Ecological Entomology",
"Ecological Management & Restoration",
"Ecological Monographs",
"Ecological Research",
"Ecology",
"Ecology Letters",
"Ecology of Freshwater Fish",
"Econometrica",
"Economic Affairs",
"Economic Anthropology",
"Economic Inquiry",
"Economic Notes",
"Economic Papers; A journal of applied economics and policy",
"Economic Record",
"Economica",
"Economics & Politics",
"Economics of Transition and Institutional Change",
"Educational Measurement: Issues and Practice",
"Educational Theory",
"Electrical Engineering in Japan",
"Electroanalysis",
"Electronics and Communications in Japan",
"ELECTROPHORESIS",
"Emergency Medicine Australasia",
"Energy Storage",
"Energy Technology",
"Entomologia Experimentalis et Applicata",
"Entomological Research",
"Entomological Science",
"Environmental and Molecular Mutagenesis",
"Environmental Microbiology",
"Environmental Policy and Governance",
"Environmental Progress & Sustainable Energy",
"Environmental Quality Management",
"Environmental Toxicology",
"Environmetrics",
"Epilepsia",
"Epileptic Disorders",
"EPPO Bulletin",
"Equine Veterinary Education",
"Equine Veterinary Journal",
"Ethics & Human Research",
"Ethology",
"Ethos",
"EuroChoices",
"European Eating Disorders Review",
"European Financial Management",
"European Journal of Clinical Investigation",
"European Journal of Dental Education",
"European Journal of Education",
"European Journal of Haematology",
"European Journal of Heart Failure",
"European Journal of Immunology",
"European Journal of Inorganic Chemistry",
"European Journal of Lipid Science and Technology",
"European Journal of Neuroscience",
"European Journal of Oral Sciences",
"European Journal of Organic Chemistry",
"European Journal of Pain",
"European Journal of Philosophy",
"European Journal of Political Research",
"European Journal of Political Research Political Data Yearbook",
"European Journal of Social Psychology",
"European Journal of Soil Science",
"European Law Journal",
"European Management Review",
"European Policy Analysis",
"Evolution & Development",
"Evolutionary Anthropology",
"Experimental Dermatology",
"Expert Systems",
"Family & Consumer Sciences Research Journal",
"Family Court Review",
"Family Process",
"Family Relations",
"Fatigue & Fracture of Engineering Materials & Structures",
"FEBS Letters",
"Feddes Repertorium",
"Feminist Anthropology",
"Financial Accountability & Management",
"Financial Management",
"Financial Markets, Institutions & Instruments",
"Fire and Materials",
"Fiscal Studies",
"Fish and Fisheries",
"Fisheries Management and Ecology",
"Fisheries Oceanography",
"Flavour and Fragrance Journal",
"Foreign Language Annals",
"Forest Pathology",
"Fortschritte der Physik",
"Freshwater Biology",
"Frontiers in Ecology and the Environment",
"Fuel Cells",
"Fundamental & Clinical Pharmacology",
"Futures & Foresight Science",
"GAMM - Mitteilungen",
"Gender & History",
"Gender, Work & Organization",
"General Anthropology",
"Genes to Cells",
"Genes, Chromosomes and Cancer",
"genesis",
"Genetic Epidemiology",
"Geoarchaeology",
"Geobiology",
"Geographical Analysis",
"Geographical Research",
"Geography Compass",
"Geological Journal",
"Geology Today",
"Geophysical Prospecting",
"Geostandards and Geoanalytical Research",
"Geriatrics & Gerontology International",
"German Life and Letters",
"Gerodontology",
"Glia",
"Global Biogeochemical Cycles",
"Global Business and Organizational Excellence",
"Global Change Biology",
"Global Ecology and Biogeography",
"Global Networks",
"Global Policy",
"Global Strategy Journal",
"Governance",
"Grass and Forage Science",
"Grassland Science",
"Greenhouse Gases: Science and Technology",
"Groundwater",
"Groundwater Monitoring & Remediation",
"Growth and Change",
"Haemophilia",
"Hastings Center Report",
"Head & Neck",
"Headache: The Journal of Head and Face Pain",
"Health Economics",
"Health Information and Libraries Journal",
"Health Promotion Journal of Australia",
"Health Services Research",
"Heat Transfer",
"Helicobacter",
"Helvetica Chimica Acta",
"Hematological Oncology",
"Hemodialysis International",
"Hepatology Research",
"Higher Education Quarterly",
"Hippocampus",
"Histopathology",
"History",
"History and Theory",
"History Compass",
"HIV Medicine",
"HLA: Immune Response Genetics",
"Human Factors and Ergonomics in Manufacturing & Service Industries",
"Human Psychopharmacology: Clinical and Experimental",
"Human Resource Development Quarterly",
"Human Resource Management",
"Human Resource Management Journal",
"Hydrological Processes",
"Ibis",
"IEEJ Transactions on Electrical and Electronic Engineering",
"Immunological Reviews",
"Immunology",
"Immunology & Cell Biology",
"In Practice",
"Industrial Relations",
"Industrial Relations Journal",
"Infancy",
"Infant and Child Development",
"Infant Mental Health Journal",
"Information Systems Journal",
"Insect Conservation and Diversity",
"Insect Molecular Biology",
"Insect Science",
"Integrative Zoology",
"Intelligent Systems in Accounting, Finance and Management",
"Internal Medicine Journal",
"International Economic Review",
"International Endodontic Journal",
"International Finance",
"International Forum of Allergy & Rhinology",
"International Insolvency Review",
"International Journal for Numerical and Analytical Methods in Geomechanics",
"International Journal for Numerical Methods in Biomedical Engineering",
"International Journal for Numerical Methods in Engineering",
"International Journal for Numerical Methods in Fluids",
"International Journal of Adaptive Control and Signal Processing",
"International Journal of Applied Ceramic Technology",
"International Journal of Applied Glass Science",
"International Journal of Applied Linguistics",
"International Journal of Applied Psychoanalytic Studies",
"International Journal of Art & Design Education",
"International Journal of Auditing",
"International Journal of Cancer",
"International Journal of Chemical Kinetics",
"International Journal of Circuit Theory and Applications",
"International Journal of Climatology",
"International Journal of Communication Systems",
"International Journal of Consumer Studies",
"International Journal of Cosmetic Science",
"International Journal of Dairy Technology",
"International Journal of Dental Hygiene",
"International Journal of Dermatology",
"International Journal of Developmental Neuroscience",
"International Journal of Eating Disorders",
"International Journal of Economic Theory",
"International Journal of Experimental Pathology",
"International Journal of Finance & Economics",
"International Journal of Geriatric Psychiatry",
"International Journal of Gynecology & Obstetrics",
"International Journal of Imaging Systems and Technology",
"International Journal of Immunogenetics",
"International Journal of Laboratory Hematology",
"International Journal of Language & Communication Disorders",
"International Journal of Management Reviews",
"International Journal of Mental Health Nursing",
"International Journal of Network Management",
"International Journal of Numerical Modelling: Electronic Networks, Devices and Fields",
"International Journal of Nursing Knowledge",
"International Journal of Nursing Practice",
"International Journal of Older People Nursing",
"International Journal of Osteoarchaeology",
"International Journal of Paediatric Dentistry",
"International Journal of Psychology",
"International Journal of Quantum Chemistry",
"International Journal of Rheumatic Diseases",
"International Journal of Robust and Nonlinear Control",
"International Journal of Satellite Communications and Networking",
"International Journal of Selection and Assessment",
"International Journal of Social Welfare",
"International Journal of Systematic Theology",
"International Journal of Tourism Research",
"International Journal of Training and Development",
"International Journal of Urban and Regional Research",
"International Journal of Urological Nursing",
"International Journal of Urology",
"International Migration",
"International Nursing Review",
"International Review of Finance",
"International Review of Hydrobiology",
"International Review of Mission",
"International Social Science Journal",
"International Social Security Review",
"International Statistical Review",
"International Transactions in Operational Research",
"Internet Technology Letters",
"IPPR Progressive Review",
"Irrigation and Drainage",
"Island Arc",
"Israel Journal of Chemistry",
"IUBMB Life",
"JACCP: Journal of the American College of Clinical Pharmacy",
"Japan Journal of Nursing Science",
"Japanese Journal of Sociology",
"JCMS: Journal of Common Market Studies",
"Journal der Deutschen Dermatologischen Gesellschaft",
"Journal For Eighteenth-Century Studies",
"Journal for Specialists In Pediatric Nursing",
"Journal for the Anthropology of North America",
"Journal for the Scientific Study of Religion",
"Journal for the Theory of Social Behaviour",
"Journal of Accounting Research",
"Journal of Addictions & Offender Counseling",
"Journal of Adolescence",
"Journal of Adolescent & Adult Literacy",
"Journal of Advanced Manufacturing and Processing",
"Journal of Advanced Nursing",
"Journal of Agrarian Change",
"Journal of Agricultural Economics",
"Journal of Agronomy and Crop Science",
"Journal of Analytical Psychology",
"Journal of Anatomy",
"Journal of Animal Breeding and Genetics",
"Journal of Animal Ecology",
"Journal of Animal Physiology and Animal Nutrition",
"Journal of Applied Behavior Analysis",
"Journal of Applied Corporate Finance",
"Journal of Applied Crystallography",
"Journal of Applied Ecology",
"Journal of Applied Econometrics",
"Journal of Applied Entomology",
"Journal of Applied Philosophy",
"Journal of Applied Polymer Science",
"Journal of Applied Research in Intellectual Disabilities",
"Journal of Applied Social Psychology",
"Journal of Applied Toxicology",
"Journal of Basic Microbiology",
"Journal of Behavioral Decision Making",
"Journal of Biochemical and Molecular Toxicology",
"Journal of Biogeography",
"Journal of Biomedical Materials Research Part A",
"Journal of Biomedical Materials Research Part B: Applied Biomaterials",
"Journal of Biophotonics",
"Journal of Business Finance & Accounting",
"Journal of Business Logistics",
"Journal of Cardiovascular Electrophysiology",
"Journal of Cellular Biochemistry",
"Journal of Cellular Physiology",
"Journal of Chemical Technology and Biotechnology",
"Journal of Chemometrics",
"Journal of Child and Adolescent Psychiatric Nursing",
"Journal of Child Psychology and Psychiatry",
"Journal of Clinical Apheresis",
"Journal of Clinical Nursing",
"Journal of Clinical Periodontology",
"Journal of Clinical Psychology",
"Journal of Clinical Ultrasound",
"Journal of Combinatorial Designs",
"Journal of Community & Applied Social Psychology",
"Journal of Community Psychology",
"Journal of Computational Chemistry",
"Journal of Computer Assisted Learning",
"Journal of Consumer Affairs",
"Journal of Consumer Behaviour",
"Journal of Consumer Psychology",
"Journal of Contingencies and Crisis Management",
"Journal of Corporate Accounting & Finance",
"Journal of Counseling & Development",
"Journal of Critical Infrastructure Policy",
"Journal of Cutaneous Pathology",
"Journal of Dental Education",
"Journal of Digestive Diseases",
"Journal of Ecology",
"Journal of Economic Surveys",
"Journal of Economics & Management Strategy",
"Journal of Educational Measurement",
"Journal of Elder Policy",
"Journal of Empirical Legal Studies",
"Journal of Employment Counseling",
"Journal of Engineering Education",
"Journal of Environmental Quality",
"Journal of Esthetic and Restorative Dentistry",
"Journal of Eukaryotic Microbiology",
"Journal of Evaluation in Clinical Practice",
"Journal of Evidence-Based Medicine",
"Journal of Experimental Zoology Part A: Ecological and Intergrative Physiology",
"Journal of Experimental Zoology Part B: Molecular and Developmental Evolution",
"Journal of Family Theory & Review",
"Journal of Family Therapy",
"Journal of Field Robotics",
"Journal of Financial Research",
"Journal of Fish Biology",
"Journal of Fish Diseases",
"Journal of Food Process Engineering",
"Journal of Food Safety",
"Journal of Food Science",
"Journal of Forecasting",
"Journal of Forensic Sciences",
"Journal of Gastroenterology and Hepatology",
"Journal of Genetic Counseling",
"Journal of Geophysical Research: Atmospheres",
"Journal of Geophysical Research: Biogeosciences",
"Journal of Geophysical Research: Earth Surface",
"Journal of Geophysical Research: Oceans",
"Journal of Geophysical Research: Planets",
"Journal of Geophysical Research: Solid Earth",
"Journal of Geophysical Research: Space Physics",
"Journal of Graph Theory",
"Journal of Healthcare Risk Management",
"Journal of Hepato-Biliary-Pancreatic Sciences",
"Journal of Heterocyclic Chemistry",
"Journal of Hospital Medicine",
"Journal of Human Nutrition and Dietetics",
"Journal of Industrial Ecology",
"Journal of Inherited Metabolic Disease",
"Journal of Integrative Plant Biology",
"Journal of Intellectual Disability Research",
"Journal of Internal Medicine",
"Journal of International Development",
"Journal of International Financial Management & Accounting",
"Journal of Investigative Psychology and Offender Profiling",
"Journal of Labelled Compounds and Radiopharmaceuticals",
"Journal of Law and Society",
"Journal of Leadership Studies",
"Journal of Legal Studies Education",
"Journal of Linguistic Anthropology",
"Journal of Magnetic Resonance Imaging",
"Journal of Management Studies",
"Journal of Marital and Family Therapy",
"Journal of Marriage and Family",
"Journal of Mass Spectrometry",
"Journal of Medical Imaging and Radiation Oncology",
"Journal of Medical Primatology",
"Journal of Medical Virology",
"Journal of Metamorphic Geology",
"Journal of Microscopy",
"Journal of Midwifery & Women's Health",
"Journal of Molecular Recognition",
"Journal of Money, Credit and Banking",
"Journal of Morphology",
"Journal of Multi-Criteria Decision Analysis",
"Journal of Multicultural Counseling and Development",
"Journal of Neurochemistry",
"Journal of Neuroendocrinology",
"Journal of Neuroimaging",
"Journal of Neuropsychology",
"Journal of Neuroscience Research",
"Journal of Nursing Scholarship",
"Journal of Obstetrics and Gynaecology Research",
"Journal of Occupational and Organizational Psychology",
"Journal of Operations Management",
"Journal of Oral Pathology & Medicine",
"Journal of Oral Rehabilitation",
"Journal of Organizational Behavior",
"Journal of Orthopaedic Research ®",
"Journal of Paediatrics and Child Health",
"Journal of Parenteral and Enteral Nutrition",
"Journal of Pediatric Gastroenterology and Nutrition",
"Journal of Peptide Science",
"Journal of Periodontal Research",
"Journal of Periodontology",
"Journal of Personality",
"Journal of Petroleum Geology",
"Journal of Pharmacy Practice and Research",
"Journal of Philanthropy",
"Journal of Phycology",
"Journal of Physical Organic Chemistry",
"Journal of Phytopathology",
"Journal of Pineal Research",
"Journal of Plant Nutrition and Soil Science",
"Journal of Plant Registrations",
"Journal of Policy Analysis and Management",
"Journal of Policy and Practice In Intellectual Disabilities",
"Journal of Polymer Science",
"Journal of Product Innovation Management",
"Journal of Prosthodontics",
"Journal of Psychiatric and Mental Health Nursing",
"Journal of Public Affairs",
"Journal of Public Economic Theory",
"Journal of Public Health Dentistry",
"Journal of Quaternary Science",
"Journal of Raman Spectroscopy",
"Journal Of Regional Science",
"Journal of Religious Ethics",
"Journal of Religious History",
"Journal of Renal Care",
"Journal of Research in Reading",
"Journal of Research in Science Teaching",
"Journal of Research in Special Educational Needs",
"Journal of Research On Adolescence",
"Journal of Risk and Insurance",
"Journal of School Health",
"Journal of Sensory Studies",
"Journal of Separation Science",
"Journal of Sleep Research",
"Journal of Small Animal Practice",
"Journal of Social Issues",
"Journal of Social Philosophy",
"Journal of Sociolinguistics",
"Journal of Software: Evolution and Process",
"Journal of Supply Chain Management",
"Journal of Surfactants and Detergents",
"Journal of Surgical Oncology",
"Journal of Systematics and Evolution",
"Journal of Texture Studies",
"Journal of the American Ceramic Society",
"Journal of the American Geriatrics Society",
"Journal of The American Oil Chemists' Society",
"Journal of the American Water Resources Association",
"Journal of the Association for Information Science and Technology",
"Journal of the Chinese Chemical Society",
"Journal of the European Academy of Dermatology and Venereology",
"Journal of the Experimental Analysis of Behavior",
"Journal of the History of the Behavioral Sciences",
"Journal of the London Mathematical Society",
"Journal of the Peripheral Nervous System",
"Journal of the Royal Anthropological Institute",
"Journal of the Science of Food and Agriculture",
"Journal of the Society for Information Display",
"Journal of Time Series Analysis",
"Journal of Topology",
"Journal of Traumatic Stress",
"Journal of Ultrasound in Medicine",
"Journal of Vegetation Science",
"Journal of Veterinary Emergency and Critical Care",
"Journal of Veterinary Pharmacology and Therapeutics",
"Journal of Vinyl & Additive Technology",
"Journal of Viral Hepatitis",
"Journal of Zoology",
"Juvenile and Family Court Journal",
"Knee Surgery, Sports Traumatology, Arthroscopy",
"Knowledge and Process Management",
"Kyklos",
"LABOUR",
"Lakes & Reservoirs: Science, Policy and Management for Sustainable Use",
"Land Degradation & Development",
"Language and Linguistics Compass",
"Language Learning",
"Laser & Photonics Reviews",
"Lasers in Surgery and Medicine",
"Latin American Policy",
"Law & Policy",
"Leader to Leader",
"Legal and Criminological Psychology",
"Legislative Studies Quarterly",
"Limnology and Oceanography",
"Limnology and Oceanography Bulletin",
"Limnology and Oceanography: Methods",
"Lipids",
"Literacy",
"Literature Compass",
"Liver International",
"Lubrication Science",
"Luminescence",
"LUTS: Lower Urinary Tract Symptoms",
"Macromolecular Bioscience",
"Macromolecular Chemistry and Physics",
"Macromolecular Rapid Communications",
"Macromolecular Reaction Engineering",
"Macromolecular Symposia",
"Macromolecular Theory and Simulations",
"Magnetic Resonance in Chemistry",
"Magnetic Resonance in Medicine",
"Mammal Review",
"Managerial and Decision Economics",
"Marine Ecology",
"Marine Mammal Science",
"Mass Spectrometry Reviews",
"Materials and Corrosion",
"Materialwissenschaft und Werkstofftechnik",
"Mathematical Finance",
"Mathematical Logic Quarterly",
"Mathematical Methods in the Applied Sciences",
"Mathematika",
"Mathematische Nachrichten",
"Medical and Veterinary Entomology",
"Medical Anthropology Quarterly",
"Medical Education",
"Medical Journal of Australia",
"Medical Physics",
"Medicinal Research Reviews",
"Metaphilosophy",
"Meteoritics & Planetary Science",
"Metroeconomica",
"Microbiology and Immunology",
"Microcirculation",
"Microscopy Research and Technique",
"Microsurgery",
"Microwave and Optical Technology Letters",
"Middle East Policy",
"Milton Quarterly",
"Mind & Language",
"Mind, Brain, and Education",
"Modern Theology",
"Molecular Carcinogenesis",
"Molecular Ecology",
"Molecular Ecology Resources",
"Molecular Informatics",
"Molecular Microbiology",
"Molecular Nutrition & Food Research",
"Molecular Oral Microbiology",
"Molecular Reproduction and Development",
"Monographs of the Society for Research in Child Development",
"Movement Disorders",
"Movement Disorders Clinical Practice",
"Muscle & Nerve",
"Musculoskeletal Care",
"Museum Anthropology",
"Music Analysis",
"Mycoses",
"Nations and Nationalism",
"Natural Resources Forum",
"Natural Sciences Education",
"Naval Research Logistics",
"Near Surface Geophysics",
"Nephrology",
"Networks",
"Neurogastroenterology & Motility",
"Neurology and Clinical Neuroscience",
"Neuropathology",
"Neuropathology and Applied Neurobiology",
"Neurourology and Urodynamics",
"New Directions for Adult and Continuing Education",
"New Directions for Community Colleges",
"New Directions for Evaluation",
"New Directions for Higher Education",
"New Directions for Student Leadership",
"New Directions for Student Services",
"New Directions for Teaching and Learning",
"New Phytologist",
"New Technology, Work and Employment",
"New Zealand Geographer",
"NMR in Biomedicine",
"Nonprofit Management & Leadership",
"Nordic Journal of Botany",
"Noûs",
"Numerical Linear Algebra With Applications",
"Numerical Methods for Partial Differential Equations",
"Nursing & Health Sciences",
"Nursing In Critical Care",
"Nursing Inquiry",
"Nursing Philosophy",
"Nutrition & Dietetics",
"Nutrition Bulletin",
"Nutrition in Clinical Practice",
"Obesity",
"Obesity Reviews",
"Oceania",
"Oikos",
"OPEC Energy Review",
"Ophthalmic and Physiological Optics",
"Optimal Control Applications and Methods",
"Oral Diseases",
"Oral Science International",
"Oral Surgery",
"Orbis Litterarum",
"Orthodontics & Craniofacial Research",
"Otolaryngology-Head and Neck Surgery",
"Oxford Bulletin of Economics and Statistics",
"Oxford Journal of Archaeology",
"Pacific Economic Review",
"Pacific Focus",
"Pacific Philosophical Quarterly",
"Pacing and Clinical Electrophysiology",
"Packaging Technology and Science",
"Paediatric and Perinatal Epidemiology",
"Pain Practice",
"Palaeontology",
"Paleoceanography and Paleoclimatology",
"Papers in Palaeontology",
"Parasite Immunology",
"Parliamentary History",
"Particle & Particle Systems Characterization",
"Pathology International",
"Peace & Change",
"Pediatric Allergy and Immunology",
"Pediatric Anesthesia",
"Pediatric Blood & Cancer",
"Pediatric Dermatology",
"Pediatric Obesity",
"Pediatric Pulmonology",
"Pediatric Transplantation",
"Pediatrics International",
"Peptide Science",
"Periodontology 2000",
"Permafrost and Periglacial Processes",
"Personal Relationships",
"Personality and Mental Health",
"Personnel Psychology",
"Perspectives On Sexual and Reproductive Health",
"Pest Management Science",
"Pharmaceutical Statistics",
"Pharmacoepidemiology and Drug Safety",
"Pharmacotherapy: The Journal of Human Pharmacology and Drug Therapy",
"Philosophical Investigations",
"Philosophical Issues",
"Philosophical Perspectives",
"Philosophy & Public Affairs",
"Philosophy and Phenomenological Research",
"Philosophy Compass",
"Photochemistry and Photobiology",
"Photodermatology, Photoimmunology & Photomedicine",
"Phycological Research",
"physica status solidi (a) applications and materials science",
"physica status solidi (b) basic solid state physics",
"physica status solidi (RRL) rapid research letters",
"Physik in unserer Zeit",
"Physiologia Plantarum",
"Physiological Entomology",
"Physiotherapy Research International",
"Phytochemical Analysis",
"Phytotherapy Research",
"Pigment Cell & Melanoma Research",
"Plant Biology",
"Plant Breeding",
"Plant Pathology",
"Plant Species Biology",
"Plant, Cell & Environment",
"Plasma Processes and Polymers",
"PM&R",
"PoLAR: Political and Legal Anthropology Review",
"Policy & Internet",
"Policy Studies Journal",
"Political Psychology",
"Politics & Policy",
"Polymer Composites",
"Polymer Engineering & Science",
"Polymer International",
"Polymers for Advanced Technologies",
"Popular Culture Review",
"Population and Development Review",
"Population Ecology",
"Population, Space and Place",
"Poverty & Public Policy",
"Prenatal Diagnosis",
"Presidential Studies Quarterly",
"Proceedings in Applied Mathematics & Mechanics",
"Proceedings of the London Mathematical Society",
"Process Safety Progress",
"Progress in Photovoltaics: Research and Applications",
"Propellants, Explosives, Pyrotechnics",
"Protein Science",
"Proteins: Structure, Function, and Bioinformatics",
"Proteomics",
"PROTEOMICS - Clinical Applications",
"Psychiatry and Clinical Neurosciences",
"Psychogeriatrics",
"Psychology & Marketing",
"Psychology and Psychotherapy: Theory, Research and Practice",
"Psychology in the Schools",
"Psycho-Oncology",
"Psychophysiology",
"Public Administration",
"Public Administration and Development",
"Public Administration Review",
"Public Budgeting & Finance",
"Public Health Nursing",
"Quality and Reliability Engineering International",
"Quarterly Journal of the Royal Meteorological Society",
"R&D Management",
"Radio Science",
"Random Structures & Algorithms",
"Rapid Communications in Mass Spectrometry",
"Ratio",
"Ratio Juris",
"Reading Research Quarterly",
"Real Estate Economics",
"Regulation & Governance",
"Religion Compass",
"Religious Studies Review",
"Remediation",
"Renaissance Studies",
"Reproduction in Domestic Animals",
"Research in Nursing & Health",
"Resource Geology",
"Respirology",
"Restoration Ecology",
"Review of Development Economics",
"Review of Education",
"Review of European, Comparative & International Environmental Law",
"Review of Financial Economics",
"Review of Income and Wealth",
"Review of International Economics",
"Review of Policy Research",
"Reviews in Aquaculture",
"Reviews in Medical Virology",
"Reviews in Religion & Theology",
"Reviews of Geophysics",
"Risk Analysis",
"Risk Management and Insurance Review",
"Risk, Hazards & Crisis in Public Policy",
"River Research and Applications",
"Rural Sociology",
"Scandinavian Journal of Caring Sciences",
"Scandinavian Journal of Immunology",
"Scandinavian Journal of Medicine & Science in Sports",
"Scandinavian Journal of Psychology",
"Scandinavian Journal of Statistics",
"Scandinavian Political Studies",
"School Science and Mathematics",
"Science Education",
"Scottish Journal of Political Economy",
"Sculpture, Monuments and Open Space",
"Security and Privacy",
"Sedimentology",
"Seminars in Dialysis",
"Separation Science Plus",
"Sexuality, Gender & Policy",
"Singapore Journal of Tropical Geography",
"Small",
"Small Methods",
"Social and Personality Psychology Compass",
"Social Development",
"Social Issues and Policy Review",
"Social Policy & Administration",
"Social Science Quarterly",
"Sociologia Ruralis",
"Sociological Forum",
"Sociological Inquiry",
"Sociology Compass",
"Sociology Lens",
"Sociology of Health & Illness",
"Software Testing, Verification & Reliability",
"Software: Practice and Experience",
"Soil Science Society of America Journal",
"Soil Use and Management",
"Solar RRL",
"Sonography",
"South African Journal of Economics",
"Southern Economic Journal",
"Special Care in Dentistry",
"Starch - Stärke",
"Stat",
"Statistica Neerlandica",
"Statistical Analysis and Data Mining",
"Statistics in Medicine",
"Steel Construction: Design and Research",
"Steel Research International",
"Strain",
"Strategic Change",
"Strategic Entrepreneurship Journal",
"Strategic Management Journal",
"Stress and Health",
"Structural Concrete",
"Studia Linguistica",
"Studies in Applied Mathematics",
"Studies In Ethnicity and Nationalism",
"Studies in Family Planning",
"Suicide and Life-Threatening Behavior",
"Support for Learning",
"Surface and Interface Analysis",
"Surgical Practice",
"Sustainable Development",
"Swiss Political Science Review",
"Symbolic Interaction",
"Synapse",
"Syntax",
"System Dynamics Review",
"Systematic Entomology",
"Systems Engineering",
"Systems Research and Behavioral Science",
"TAXON",
"Teaching Statistics",
"Teaching Theology & Religion",
"Tectonics",
"Terra Nova",
"TESOL Journal",
"TESOL Quarterly",
"The American Journal of Economics and Sociology",
"The American Journal on Addictions",
"The Anatomical Record",
"The Australian Economic Review",
"The Australian Journal of Agricultural and Resource Economics",
"The Australian Journal of Anthropology",
"The British Journal of Sociology",
"The Canadian Journal of Chemical Engineering",
"The Canadian Journal of Statistics/La revue canadienne de statistique",
"The Career Development Quarterly",
"The Chemical Record",
"The Clinical Teacher",
"The Curriculum Journal",
"The Developing Economies",
"The Economic History Review",
"The Ecumenical Review",
"The Electronic Journal of Information Systems in Developing Countries",
"The FASEB Journal",
"The FEBS Journal",
"The Financial Review",
"The Geographical Journal",
"The German Quarterly",
"The Heythrop Journal",
"The Howard Journal of Crime and Justice",
"The International Journal of Health Planning and Management",
"The International Journal of Medical Robotics and Computer Assisted Surgery",
"The Journal of American Culture",
"The Journal of Clinical Pharmacology",
"The Journal of Comparative Neurology",
"The Journal of Creative Behavior",
"The Journal of Dermatology",
"The Journal of Finance",
"The Journal of Futures Markets",
"The Journal of Gene Medicine",
"The Journal of Humanistic Counseling",
"The Journal of Industrial Economics",
"The Journal of Latin American and Caribbean Anthropology",
"The Journal of Pathology",
"The Journal of Physiology",
"The Journal of Political Philosophy",
"The Journal of Popular Culture",
"The Journal of Rural Health",
"The Journal of Wildlife Management",
"The Journal of World Intellectual Property",
"The Laryngoscope",
"The Manchester School",
"The Milbank Quarterly",
"The Modern Language Journal",
"The Modern Law Review",
"The Muslim World",
"The Obstetrician & Gynaecologist",
"The Philosophical Forum",
"The Photogrammetric Record",
"The Plant Journal",
"The Political Quarterly",
"The Prostate",
"The RAND Journal of Economics",
"The Reading Teacher",
"The Russian Review",
"The Scandinavian Journal of Economics",
"The Southern Journal of Philosophy",
"The Structural Design of Tall and Special Buildings",
"The World Economy",
"Theoria",
"Therapeutic Apheresis and Dialysis",
"Thunderbird International Business Review",
"Tijdschrift voor Economische en Sociale Geografie",
"Topics in Cognitive Science",
"Traditional & Kampo Medicine",
"Traffic",
"Transactions in GIS",
"Transactions of the Institute of British Geographers",
"Transactions of the Philological Society",
"Transactions on Emerging Telecommunications Technologies",
"Transfusion",
"Transfusion Medicine",
"Transplant Infectious Disease",
"Transportation Journal",
"Tropical Medicine & International Health",
"Ultrasound in Obstetrics & Gynecology",
"Veterinary and Comparative Oncology",
"Veterinary Clinical Pathology",
"Veterinary Dermatology",
"Veterinary Ophthalmology",
"Veterinary Radiology & Ultrasound",
"Veterinary Record",
"Veterinary Record Case Reports",
"Veterinary Surgery",
"Vietnam Journal of Chemistry",
"Visual Anthropology Review",
"Vox Sanguinis",
"Water and Environment Journal",
"Water Environment Research",
"Weather",
"Weed Biology and Management",
"Weed Research",
"Wildlife Monographs",
"WIREs Climate Change",
"WIREs Cognitive Science",
"WIREs Computational Molecular Science",
"WIREs Computational Statistics",
"WIREs Data Mining and Knowledge Discovery",
"WIREs Energy and Environment",
"WIREs Forensic Science",
"WIREs Mechanisms of Disease",
"WIREs Nanomedicine and Nanobiotechnology",
"WIREs RNA",
"WIREs Water",
"World Affairs",
"World Englishes",
"World Food Policy",
"World Journal of Surgery",
"World Medical & Health Policy",
"World Water Policy",
"Worldviews on Evidence-Based Nursing",
"Wound Repair and Regeneration",
"Xenotransplantation",
"X-Ray Spectrometry",
"Yeast",
"ZAMM - Journal of Applied Mathematics and Mechanics",
"Zeitschrift für anorganische und allgemeine Chemie",
"Zoo Biology",
"Zoologica Scripta",
"Zoonoses and Public Health",
]	
